### ISSUE TITLE
Error 'EasyDict' object has no attribute 'DATA_CONFIG' when trying to test with the pretrained on Kitty dataset

### ISSUE THREAD

**Issue by octavianplesea** [TRAILab/CaDDN#101]
Hello,
I'm getting this error
`Traceback (most recent call last):
  File "test.py", line 199, in <module>
    main()
  File "test.py", line 159, in main
    eval_output_dir = eval_output_dir / ('epoch_%s' % epoch_id) / cfg.DATA_CONFIG.DATA_SPLIT['test']
AttributeError: 'EasyDict' object has no attribute 'DATA_CONFIG'`

when tring to run the pretrained model on Kitty dataset.
I've found some similar problems at this [link](https://github.com/open-mmlab/OpenPCDet/issues/106)
After having the look in the requirements.txt file, I saw that already the last EasyDict version is installed and this does not seem to solve the issue.
Can you please support me with this?

I will also attach the ipynb file which I used in Google Colaboratory.
[CADDN_issue.zip](https://github.com/TRAILab/CaDDN/files/7966589/CADDN_issue.zip)

**Comment by octavianplesea** [comment]
Found out I was giving a wrong config file.

**Comment by jayhsu0627** [comment]
the correct config is ```cfgs/kitti_models/CaDDN.yaml``` for the `CaDDN.ptb`
