### ISSUE TITLE
Somethings wrong when generate the kitti data infos

### ISSUE THREAD

**Issue by xiaoMrzhang** [TRAILab/CaDDN#20]
When I do dataset preparation according to GETTING_STARTED.md and run commond `python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml`, the program crash with info"'EasyDict' object has no attribute 'DEPTH_MAP'". Finally I add DEPTH_MAP from CaDDN.yaml to kitti_dataset.yaml and it works, but I don't konw if it's correct.

**Comment by codyreading** [comment]
Yep that should be fine, the depth map's aren't used when generating the kitti data infos. I'll make a revision to fix this error.

**Comment by codyreading** [comment]
Closing this issue as per https://github.com/TRAILab/CaDDN/pull/21
