### ISSUE TITLE
About depth map file

### ISSUE THREAD

**Issue by hunterkeith2017** [TRAILab/CaDDN#22]
Wonderfull job!
But i still have a personal question, how to produce the depth maps ground true for kitti training set? 
In an another word, how i reproduce this depth maps ground true to supervise my network for other dataset?
The download file may not belong to the official KITTI file. 
Could you help me? 

KITTI Dataset
Please download the official KITTI 3D object detection dataset and organize the downloaded files as follows:
Download the precomputed depth maps for the KITTI training set

**Comment by codyreading** [comment]
Thanks for taking interest in my project!

For the KITTI Dataset, I used the depth completion method [IP-Basic](https://github.com/kujason/ip_basic) to generate depth maps from LiDAR data. You could do the same for another dataset, or alternatively use a more current depth completion method to do the same thing.
