### ISSUE TITLE
Question: inference time

### ISSUE THREAD

**Issue by frankfengdi** [TRAILab/CaDDN#23]
Really nice work! Thank you for releasing the code.
I wonder how large is the network in total, and how long does it take for inference?

**Comment by codyreading** [comment]
These numbers depend on the batch size and the hardware you are running inference with. I can give you these for my personal workstation for example:

```
GPU: NVIDIA Titan XP
Batch Size: 2
Max GPU Memory Consumption: 7712 MB
Avg. Iteration Speed: 1.82 it/s
Total Time for KITTI Val Inference: 17 min, 15 seconds
```

Feel free to run this yourself and see what kind of performance you get.

**Comment by rockywind** [comment]
It's very odd. My GPU is NVIDIA RTX3090, but it took 10s for every image.
![image](https://user-images.githubusercontent.com/14838781/120332600-7dfcf900-c321-11eb-9fa1-89fc170a0eda.png)

**Comment by codyreading** [comment]
Hi @rockywind,

Are you using `torch==1.4.0`? If you are using a newer torch version, the inference will take a very long time.
If you want to keep your current environment with a newer torch version, you can change this [line](https://github.com/TRAILab/CaDDN/blob/5a96b37f16b3c29dd2509507b1cdfdff5d53c558/pcdet/models/__init__.py#L27)
from:
```
            batch_dict[key] = kornia.image_to_tensor(val).float().cuda()
```
to:
```
            batch_dict[key] = kornia.image_to_tensor(val).float().cuda().contiguous()<br class="Apple-interchange-newline">
```

 I am working on changing this in the repo, but you can make this quick fix for now.

**Comment by rockywind** [comment]
Thanks a lot for your help. It's work.

**Comment by codyreading** [comment]
Great glad I can help

**Comment by MaltoseFlower** [comment]
really help me, thks. #

> Hi @rockywind,
> 
> Are you using `torch==1.4.0`? If you are using a newer torch version, the inference will take a very long time. If you want to keep your current environment with a newer torch version, you can change this [line](https://github.com/TRAILab/CaDDN/blob/5a96b37f16b3c29dd2509507b1cdfdff5d53c558/pcdet/models/__init__.py#L27) from:
> 
> ```
>             batch_dict[key] = kornia.image_to_tensor(val).float().cuda()
> ```
> 
> to:
> 
> ```
>             batch_dict[key] = kornia.image_to_tensor(val).float().cuda().contiguous()
> ```
> 
> I am working on changing this in the repo, but you can make this quick fix for now.
