### ISSUE TITLE
How to get the depth map?

### ISSUE THREAD

**Issue by Majiawei** [TRAILab/CaDDN#27]
I've downloaded the depth map you provided, but I don't know how to generate it

How can I convert the Lidar point cloud data into sparse depth map as mentioned in the paper, and then use the sparse depth to complete the dense depth map?

Can you provide the code?

**Comment by codyreading** [comment]
Hello and thanks for the interest!

I've mentioned this issue here https://github.com/TRAILab/CaDDN/issues/22#issuecomment-816778462, please refer to this.
