### ISSUE TITLE
Depth Map Completion Setup

### ISSUE THREAD

**Issue by tianweiy** [TRAILab/CaDDN#28]
Hi, from the paper, it mentioned that you use https://github.com/kujason/ip_basic for depth completion. Which version of the algorithm are you using for KITTI and Waymo? Gaussian, bilateral, multiscale? Thanks.

**Comment by codyreading** [comment]
Hello!

I ended up using the version of IP Basic inside [MonoPSR](https://github.com/kujason/monopsr/blob/master/src/ip_basic/ip_basic.py). This uses the follow parameters:
```
fill_type = 'multiscale'
extrapolate = False,
blur_type = 'bilateral'
```

**Comment by tianweiy** [comment]
thanks
