### ISSUE TITLE
result on waymo dataset

### ISSUE THREAD

**Issue by walterchenchn** [TRAILab/CaDDN#29]
Thanks for your contribution!

Waymo dataset is quite large and more diverse. Why didn't you use a look-around camera for detection on the Waymo？

**Comment by codyreading** [comment]
Hi Walter!

We didn't do the full 360 degree camera rig on Waymo due to GPU memory constraints on processing multiple images simultaneously. This would require us to reduce our model capacity, greatly impacting results.

**Comment by walterchenchn** [comment]
Can you publish the model config of waymo dataset?

**Comment by codyreading** [comment]
Hi Walter,

I don't have a config for the Waymo dataset for the updated version released here. The config should be the similar to the KITTI config, but point cloud range should be changed to `POINT_CLOUD_RANGE: [2, -25.6, -4.0, 55.76, 25.6, 4.0]`. Additionally, the Waymo images were down-sampled to meet memory constraints.

Hope this help!

**Comment by vobecant** [comment]
Hi @codyreading,

do you intend to release the config file for the Waymo dataset?

Thank you very much!

**Comment by codyreading** [comment]
Hi and thanks for the interest!

Yes, I plan to release the config, however this also requires adding support for Image Data Loading from the Waymo Dataset.

**Comment by vobecant** [comment]
Hi @codyreading,
thank you very much for your response, I am looking forward to the release. Have you got any idea of when it might be?
Regarding the support of data loading: don't you already have this in `pcdet/datasets/waymo/waymo_dataset.py`? If not, would you please release this loader along with the configs?

Thanks!

**Comment by codyreading** [comment]
Hello!

The functionality in `pcdet/datasets/waymo/waymo_dataset.py` doesn't currently support images, only LiDAR point clouds. The code that I used for the Waymo dataset experiments in the paper is outdated, so this would not be able to be used here.

In terms of timeline, I'm not sure as this is a lower priority item for me at the moment. If you need this urgently I would recommend implementing this yourself.

**Comment by walterchenchn** [comment]
Hi @codyreading 
I hope to use the look-around camera data of the waymo dataset. But the picture frame of camera on the side is different with the other. How do you deal with these differences?

**Comment by codyreading** [comment]
Hi @walterchenchn,

Again, we didn't use the other camera and only used the front camera for our experiments. If you would like to use multiple cameras, you could try using one network for all the cameras, but you might have to have separate networks for each camera.

**Comment by walterchenchn** [comment]
thanks!

**Comment by vobecant** [comment]
> Hello!
> 
> The functionality in `pcdet/datasets/waymo/waymo_dataset.py` doesn't currently support images, only LiDAR point clouds. The code that I used for the Waymo dataset experiments in the paper is outdated, so this would not be able to be used here.
> 
> In terms of timeline, I'm not sure as this is a lower priority item for me at the moment. If you need this urgently I would recommend implementing this yourself.

Hi @codyreading, thank you for your reply. Do you think that you could please share with me at least the outdated version of the dataloader? I might be able to convert it to a usable version.
Thanks!

**Comment by codyreading** [comment]
The outdated version of the data loader is essentially the KITTI data loader, as I converted the Waymo Dataset to a KITTI format for use in my network. If you plan to start there, I would recommend using the current KITTI dataloader.
