### ISSUE TITLE
Training Time Problem

### ISSUE THREAD

**Issue by YunzheWu-404** [TRAILab/CaDDN#34]
Hello

I would like to ask about a training time issue. I am trying to train this model with 3 RTX 3090s and the batch size is set to be 9. However, it shows that the training time is going to be around 370 hours which is much longer than what you posted.

I would really appreciate it if you could help with it. 

Many thanks

**Comment by YunzheWu-404** [comment]
Thanks, I have found dealt with it.

**Comment by ma8sa** [comment]
> Thanks, I have found dealt with it.

How did you resolve it, I am facing the same issue
