### ISSUE TITLE
Could you please provide the code for visualization?

### ISSUE THREAD

**Issue by kaixinbear** [TRAILab/CaDDN#41]

**Comment by codyreading** [comment]
You can modify the visualization code from [OpenPCDet](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/demo.py) to visualize the detections. You would just need to add the image data loading here I believe.

**Comment by kaixinbear** [comment]
This demo.py seems to only visualize points, not image instead?

**Comment by codyreading** [comment]
There is currently no support for image visualization at the moment. I'd be happy to take contributions to add image visualization code to this repository.

**Comment by kaixinbear** [comment]
Thx, waiting for it.
