### ISSUE TITLE
Questions about MaptoBEV operation

### ISSUE THREAD

**Issue by gujiaqivadin** [TRAILab/CaDDN#42]
Hello! 
     Thanks for your sharing great mono3d detection work CaDDN! After I read the code, I have a simple question about the Map-to-BEV operation. I found two operations here 'Conv2DCollapse' and 'HeightCompression', and they do the same thing to collapse voxel-wise features into BEV features. I want to know where is the difference between these two operations. And  the code of reshape operation '.view' and '.flatten' , is there any difference between these two ways?

Thanks a lot!

**Comment by codyreading** [comment]
Hi and thanks for the interest!

The only real difference between these is that `'Conv2DCollapse` includes a 1x1 convolutional block for channel reduction. Otherwise, they should function the same. Reshaping via `.view` or `.flatten` ends up being the same.

**Comment by gujiaqivadin** [comment]
Thanks a lot!
