### ISSUE TITLE
Generation of labels on depth_2 file

### ISSUE THREAD

**Issue by YunzheWu-404** [TRAILab/CaDDN#43]
Hi 

Thank you very much for sharing your great work with us. 

I am a big fun of your use of semantic segmentation and pcdet in 3D detection.

Could I ask detatils about how you trasform the sparse depth labels provided in kitti to the denth labels in depth_2?

I would really appreciate if you could help.

Best.

**Comment by codyreading** [comment]
Hi and thanks for the interest!

For the KITTI Dataset, I used the depth completion method IP-Basic to generate dense depth maps from LiDAR data. You could do the same for another dataset, or alternatively use a more current depth completion method to do the same thing. I used the following parameters on the KITTI dataset:

```
fill_type = 'multiscale'
extrapolate = False
blur_type = 'bilateral'
```
