### ISSUE TITLE
How to generate a depth map for the Kitti dataset?

### ISSUE THREAD

**Issue by rockywind** [TRAILab/CaDDN#44]
Thanks for your help on the previous issue.
Was the depth map of the Kitti dataset synthesized from 5 frames of LiDAR Scan? Because Lidar Scan and depth map data looked different.

**Comment by codyreading** [comment]
We used a single LiDAR frame to generate the depth map. We used a depth completion method which filled in the gaps of the sparse LiDAR scan, which might explain why the LiDAR scan looks different to the depth map.
