### ISSUE TITLE
Acquisition of depth data from waymo dataset

### ISSUE THREAD

**Issue by Majiawei** [TRAILab/CaDDN#45]
Is it possible to provide scripts for depth map acquisition in waymo dataset?
Including how to convert lidar data into sparse depth map?
And how to complete sparse depth map to dense depth map？
Thanks！

**Comment by codyreading** [comment]
Hi Majiawei.

I used this [repo](https://github.com/kujason/ip_basic) to generate dense depth maps from LiDAR. This repo only supports KITTI, so I ended up converting the Waymo dataset into a KITTI format to be used here. I don't currently have any scripts that loads the Waymo dataset directly.

**Comment by Majiawei** [comment]
> Hi Majiawei.
> 
> I used this [repo](https://github.com/kujason/ip_basic) to generate dense depth maps from LiDAR. This repo only supports KITTI, so I ended up converting the Waymo dataset into a KITTI format to be used here. I don't currently have any scripts that loads the Waymo dataset directly.

I know the code base you are talking about, but there is no code to map lidar data to image plane to generate sparse depth map, right?
This code can only complete the conversion from sparse depth map to dense depth map

**Comment by codyreading** [comment]
Ah I see, take a look at this [script](https://github.com/kujason/monopsr/blob/master/demos/depth_completion/save_lidar_depth_maps.py) actually which does the projection and then converts the sparse depth maps to dense depth maps.

Alternatively, there is functionality built-in with this repo that should give you the projection functionality you desire. Taking a look at the projection code [here](https://github.com/TRAILab/CaDDN/blob/master/pcdet/utils/calibration_kitti.py#L86). This function projects LiDAR points into the image, and gives you the pixel coordinates and the depth, which should allow you to construct the sparse depth map here. Although, this code was written for KITTI so will likely need to be modifed for use for Waymo.
