### ISSUE TITLE
About the Coordinate Space

### ISSUE THREAD

**Issue by czy341181** [TRAILab/CaDDN#46]
When building the voxel, it is constructed in the point cloud coordinate system. So the output heatmap map is also in the point cloud coordinate system (so during training, the 3D box is converted to the lidar coordinate system as the label). 
But  the final 3D Box in the inference stage is based on lidar coordinate, so it still needs to be converted to camera coodinate?

Do I understand correctly?

**Comment by czy341181** [comment]
Sorry, In my description。 
point cloud coordinate system ==  lidar coordinate system
[2, -30.08, -3.0, 46.8, 30.08, 1.0]

**Comment by czy341181** [comment]
I think my understanding is right.  I see the code 
https://github.com/TRAILab/CaDDN/blob/5a96b37f16b3c29dd2509507b1cdfdff5d53c558/pcdet/datasets/kitti/kitti_dataset.py#L315


Is it right?  Thank you very much.

**Comment by czy341181** [comment]
I think my understanding is right. I see the code

https://github.com/TRAILab/CaDDN/blob/5a96b37f16b3c29dd2509507b1cdfdff5d53c558/pcdet/datasets/kitti/kitti_dataset.py#L350

Is it right? Thank you very much.

**Comment by codyreading** [comment]
Yes that is correct. I inherited most of the code from [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) which does all of its representations in the LIDAR coordinate system. The same system is used here.
