### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by chetanmreddy** [TRAILab/CaDDN#50]
Hello Thank you for your great work.

I am trying to train your model on a custom dataset where we have 3d bounding boxes for images. But we don't have depth maps or sparse LIDAR maps. Can I still use your model for 3d object detection on our dataset?

Thanks again for your help.

**Comment by codyreading** [comment]
Hi and thanks for the interest!

You can try to use CaDDN without the depth loss, but I would not expect great results. This was actually an ablation study I did for the [paper](https://arxiv.org/pdf/2103.01100.pdf), in Table 3, Exp.2, in which performance was about half without the depth loss.
