### ISSUE TITLE
Question of evaluate result on Waymo dataset

### ISSUE THREAD

**Issue by cheniynan** [TRAILab/CaDDN#65]
Hello! I wonder know whether you remove the objects that out of the front camera’s field of view in validation set when you evaluate your model on waymo dataset.

**Comment by codyreading** [comment]
Yup that's correct, only objects in the FOV of the front camera are included during evaluation.

**Comment by cheniynan** [comment]
Thanks for help!

**Comment by ZCMax** [comment]
> Hello! I wonder know whether you remove the objects that out of the front camera’s field of view in validation set when you evaluate your model on waymo dataset.

Hello, could you please tell me how to remove the objects out of fov while evaluation?
