### ISSUE TITLE
IS there any pretrained model on Waymo ?

### ISSUE THREAD

**Issue by Cc-Hy** [TRAILab/CaDDN#69]
HELLO,
I have some new ideas on the CaDDN network, and want to test it on the Waymo val dataset. However, the dataset is too large and my device is limited. So i'd like to know if there is any pretrained model on Waymo to ease the process. Even not very well trained ones would be very helpful.
Thank you.

**Comment by codyreading** [comment]
Hello!

Apologies, I do not have any trained Waymo models compatible with this version of the codebase.
