### ISSUE TITLE
 I set the syn_bn   as True when doing multi GPU training, but the 3D AP is lower.

### ISSUE THREAD

**Issue by rockywind** [TRAILab/CaDDN#72]
My environment is:
8*A6000
BATCH_SIZE_PER_GPU:4
batch_size:32
pytorch1.7.1
cuda11.1
![image](https://user-images.githubusercontent.com/14838781/132943094-62a2b8ba-1430-457e-a892-101e6ad9911d.png)

**Comment by codyreading** [comment]
I didn't do experiments with this large of a batch size, so unsure how performance is affected at these large batch sizes. I would recommend trying multiple runs at different batch sizes and different settings of `sync_bn` to see the performance if you are interested at these large batch sizes.
