### ISSUE TITLE
sampling

### ISSUE THREAD

**Issue by sungheuiK** [TRAILab/CaDDN#73]
Hi! Thanks for sharing your great work:)

While reading your work, I had some  question regarding the process of the model.
After generating frustum, sampling process is needed to generate voxel. So what exactly is the purpose of sampling when generating voxel? 

thanks!

**Comment by codyreading** [comment]
Please refer to Figure 4 in the [paper ](https://arxiv.org/pdf/2103.01100.pdf). The sampling is required to generate each voxel feature by transforming sampling points in the voxel grid to the frustum grid and sampling the associated features.
