### ISSUE TITLE
How does the GT dense depth map come ?

### ISSUE THREAD

**Issue by Cc-Hy** [TRAILab/CaDDN#74]
HELLO,
I noticed the GT depth maps that KITTI offers are in form of points projection, but the training depth maps used are dense images.
So I wonder how to get the dense depth maps from the projection form.
Thank you!

![image](https://user-images.githubusercontent.com/82150240/133456398-65ad8a87-0bd9-4379-8f19-a14b8e82d741.png)

**Comment by codyreading** [comment]
Hello!

Please refer to the following issues: https://github.com/TRAILab/CaDDN/issues/22, https://github.com/TRAILab/CaDDN/issues/28, https://github.com/TRAILab/CaDDN/issues/43. We use a depth completion method called IP-Basic to get the dense depth images.

**Comment by Cc-Hy** [comment]
Thanks.
