### ISSUE TITLE
Evaluation on test set

### ISSUE THREAD

**Issue by qwedaq** [TRAILab/CaDDN#89]
Can you please tell me how can I evaluate on test set? I have changed in the kitti_dataset.yaml file, 'test':test but it doesn't seem to work.

**Comment by qwedaq** [comment]
Sorry for closing it, can you please direct me with this?

**Comment by VE-yyq** [comment]
> n you please tell me how can I evaluate on test set? I have changed in the kitti_dataset.yaml file, 'test':test but it doesn't seem to work.

hello,I have the same question. Since there are no labels in test set,  how can I get the evaluation result on test set? Have you solved it?

**Comment by VE-yyq** [comment]
> Can you please tell me how can I evaluate on test set? I have changed in the kitti_dataset.yaml file, 'test':test but it doesn't seem to work.

Hello, I have the same question, since there are no labels on test set, how can I get the evaluation result on it? Have you solved it?
